[package]
name = "projects"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"
resolver = "2"

[dependencies]
ink = { version = "5.1.1", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }
kreivo-apis = { git = "https://github.com/virto-network/kreivo", branch = "dev", default-features = false, features = [
  "contract",
] }
virto-common = { git = "https://github.com/virto-network/kreivo", branch = "dev", default-features = false, features = ["scale"] }

[dev-dependencies]
ink_e2e = { version = "5.1.1" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "kreivo-apis/std",
    "virto-common/std",
]
ink-as-dependency = []
e2e-tests = []